### ISSUE TITLE
Standalone NTIA compliance check

### ISSUE THREAD

**Issue by mjschlosser8** [anthonyharrison/sbomaudit#3]
Hello! 

Could we get a standalone NTIA compliance check that returns a true/false boolean on pass/fail? I often need to check compliance without validating the entire SBOM document.

**Comment by anthonyharrison** [comment]
@mjschlosser8 In order to confirm that the SBOM is NTIA compliant, it is necessary to process the whole SBOM as the checks require examination of all of the metadata, file, package and relationship data.

Using the `--output-file` option will produce a JSON file with the results of the audit. The following python snippet will process the JSON file and report 'Pass' or 'Fail'

```python
import json
json_file = "filename.json"
data = json.load(open(json_file))
ntia_compliance  = data["summary"][0]["state"]
```

To allow sbomaudit to be included in a script, I will add a return value to indicate if the audit has detected NTIA compliance (0 for Fail, 1 for Pass)

**Comment by anthonyharrison** [comment]
Return code added to release v0.3.1
